### ISSUE TITLE
Want to convert Class component into functional component

### ISSUE THREAD

**Issue by sanjeevyadavIT** [AurangzaibRamzan/Anime-jisho#10]
Hello, I would like to contribute to the app, I was checking `MainScreen` and it can be easily converted into functional component.

**Reason**
1. With react hooks, state and life-cycle can be managed in functional component
2. Not major: [How Functional component differ from Class - Dan abramov](https://overreacted.io/how-are-function-components-different-from-classes/)
3. I was looking for best practices when I started reading you code, it would be good for others to learn best practices.

Can I create a pull request extracting `MainScreen` class component into functional component?

**Comment by AurangzaibRamzan** [comment]
yep you can do that . Happy coding :+1:
