### ISSUE TITLE
App not loading any data

### ISSUE THREAD

**Issue by sanjeevyadavIT** [AurangzaibRamzan/Anime-jisho#12]
**Describe the bug**
I try to run the app on Android, no data is loading. It is showing default no network image, and I have my internet connection on while testing the app

**Expected behavior**
List of anime should have loaded

**Current Behavior**
Nothing is getting loaded, see screenshots

**Steps to Reproduce**
1. Clone the repository
    ```bash
    git clone https://github.com/bytefuge/Anime-jisho.git && cd Anime-jisho
    ```
2. Install dependencies
    ```bash
    npm install
    ```
3. In terminal, run
    ```bash
    npm start
    ```
3. In separate terminal, run the project
    ```bash
    react-native run-android
    ```

**Screenshots**
![Screenshot_1568112055](https://user-images.githubusercontent.com/13250741/64609652-07042c00-d3eb-11e9-9896-31d84155ae7a.png)
![Screenshot_1568112062](https://user-images.githubusercontent.com/13250741/64609653-08355900-d3eb-11e9-967e-bba2e726f053.png)
![Screenshot_1568112065](https://user-images.githubusercontent.com/13250741/64609654-09ff1c80-d3eb-11e9-8189-c5b18f6d580e.png)
.
**Smartphone (please complete the following information):**
 - React Native Version: [0.59.8]
 - Device: [Android Emulator Nexus 5X]
 - OS: [PIE]
 - Version [28]

**Additional context**
Do I need to setup some server client to run this app?

**Comment by AurangzaibRamzan** [comment]
solve issue in dev and merge in master . [check](https://github.com/bytefuge/Anime-jisho/pull/13)
